name: Simple workflow example
on: push

jobs:
  Run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo single line command
        run: echo 'Hello World'
      - name: Echo multiple line commands
        run: |
          pwd
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: View SW version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: Run-shell-commands
    steps:
      - name: Echo a string
        run: Write-Output " Hello world in windows "
      - name: Error
        run: does not exists