name: Simple workflow example
on: workflow_dispatch

jobs:
  Run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo single line command
        run: echo 'Hello World'
      - name: Echo multiple line commands
        run: |
          pwd